sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: UmihXUN55WWSGuzJDm1IZ92+RVBkYgGgMTFm2OqLM2VPHgm2V2/Hm0w2X32AzNMwVNTDpble+X8LeqNkUxE8iHqu9iL9ls3xpZ2OeQJS69bZAl61ztovhbr1kbLxCgxaLUUxB5PSgy9ia/53EFF3eRZ/b2jXfqIkMr7XfBKnmOA4DVnLK5ofWq45HRJczu1/YwEApr1dbB3WNnNNPx1Ib7TwlkBTal+KYe9MlsZieefc3sleyZxJEIUcdwG5YRuLEHPSUl7orttCgkecz/B6Lrd/GJ8UgXLhi1LPmzt4BdU+w6aa/g1t4RZjeIlo0BTgbEoANVwH8NuZj7/jdXnyzSqIQlmndh5Yci+sQ55NYqvuUY8QnuHZKM9PYr0bN4oRkLYDjC+hZQZe4etHXE6Ycn791rmUdteIMu5sLWT02zTYDdjOVM244MnQUMOwg+ozFzvmtbxv+XM53RQ+pJriyRD52aHDf3/VV2teebZ0PzgRSz5LPTAkJZHan/aLN77LoEOVRmeOu7ljEBvBRk1ZYbqVkywADudSasvhGKa0PuSs4Aq0z938m7q8Zvoi5am+aQqx0YlItawAl/6MS71F7CsN3IknyHpNa6412md7y4VMeNBbSmm961nd3KiRYAYdB2JS5iLLU5d+7mq1jZdmviKlsSwpZhrM/1lbJjlM63Q=
branches:
  only:
  - development
